import { db } from '@/lib'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../lib/fontawesome'
import '../styles/globals.css'

import { Navbar, SessionProvider } from '@/components'
import { getCurrentSession } from '@/lib'
import { useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ebay-Auction',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const session = await getCurrentSession()

  return (
    <html lang='en'>
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Navbar />
          <main className='h-full w-full pt-[120px]'>{children}</main>
        </SessionProvider>
      </body>
    </html>
  )
}
